CREATE TABLE ZIPCODE(
ZIP_CODE VARCHAR(5) PRIMARY KEY,
CITY VARCHAR(25) CONSTRAINT _ZIP_CITY_NN NOT NULL,
STATE VARCHAR(2) CONSTRAINT _ZIP_STATE_NN NOT NULL
);
CREATE TABLE INSTRUCTOR_INFO(
INTRUCTOR_ID VARCHAR(8) CONSTRAINT _INSTRUCTOR_ID_PK PRIMARY KEY,
INSTRUCTOR_FIRST_NAME VARCHAR(25) CONSTRAINT _INSTRUCTOR_FN_NN NOT NULL,
INSTRUCTOR_SECOND_NAME VARCHAR(25) CONSTRAINT INSTRUCTOR_LN_NN NOT NULL,
STREET_ADDRESS VARCHAR(50),
ZIP_CODE VARCHAR(5)CONSTRAINT ZIP_INSTRUCTOR_FK FOREIGN KEY REFERENCES ZIPCODE(ZIP_CODE)
);
CREATE TABLE COURSE_INFO(
COURSE_NO INT CONSTRAINT COURSE_NO_PK PRIMARY KEY,
COURSE_NAME VARCHAR(50) CONSTRAINT COURSE_NAME_NN NOT NULL,
COURSE_PREREQUISITE VARCHAR(8),
COST FLOAT CONSTRAINT COST_NN NOT NULL
);
CREATE TABLE STUDENT_INFO (
    STUDENT_ID         NUMBER(8,0),
    STUDENT_FIRST_NAME VARCHAR2(25) CONSTRAINT STUDENT_FN_NN NOT NULL,
    STUDENT_LAST_NAME  VARCHAR2(25) CONSTRAINT STUDENT_LN_NN NOT NULL,
    STREET_ADDRESS     VARCHAR2(50),
    ZIP_CODE           VARCHAR2(5),

    CONSTRAINT STUDENT_ID_PK PRIMARY KEY (STUDENT_ID),
    CONSTRAINT ZIP_STUDENT_FK 
        FOREIGN KEY (ZIP_CODE) 
        REFERENCES ZIPCODE_INFO(ZIP_CODE)
);
CREATE TABLE SECTION_INFO (
    SECTION_ID   NUMBER(8,0),
    COURSE_NO   NUMBER(8,0),
    SECTION_NO  NUMBER(3,0) CONSTRAINT SECTION_NO_NN NOT NULL,
    INSTRUCTOR_ID NUMBER(8,0),
    LOCATION    VARCHAR2(50),
    CAPACITY    NUMBER(3,0),

    CONSTRAINT SECTION_ID_PK PRIMARY KEY (SECTION_ID),

    CONSTRAINT COURSE_SECTION_FK
        FOREIGN KEY (COURSE_NO)
        REFERENCES COURSE_INFO(COURSE_NO),

    CONSTRAINT INSTRUCTOR_SECTION_FK
        FOREIGN KEY (INSTRUCTOR_ID)
        REFERENCES INSTRUCTOR_INFO(INSTRUCTOR_ID)
);
CREATE TABLE ENROLLMENT_INFO (
    STUDENT_ID     NUMBER(8,0),
    SECTION_ID     NUMBER(8,0),
    ENROLLMENT_DATE DATE,

    CONSTRAINT ENROLLMENT_STUD_SECT_PK 
        PRIMARY KEY (STUDENT_ID, SECTION_ID),

    CONSTRAINT ENROLLMENT_STUDENT_ID_FK
        FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT_INFO(STUDENT_ID),

    CONSTRAINT ENROLLMENT_SECTION_ID_FK
        FOREIGN KEY (SECTION_ID)
        REFERENCES SECTION_INFO(SECTION_ID)
);
CREATE TABLE GRADE_INFO (
    STUDENT_ID           NUMBER(8,0),
    SECTION_ID           NUMBER(8,0),
    GRADE_TYPE_CODE     CHAR(2),
    GRADE_CODE_OCCURANCE NUMBER(38,0),
    NUMERIC_GRADE       NUMBER(3,0) DEFAULT 0 CONSTRAINT NUMERIC_GRADE_NN NOT NULL,

    CONSTRAINT GRADE_STUD_SECT_TYPE_CODE_PK 
        PRIMARY KEY (
            STUDENT_ID, 
            SECTION_ID, 
            GRADE_TYPE_CODE, 
            GRADE_CODE_OCCURANCE
        ),

    CONSTRAINT GRADE_STUDENT_ID_FK
        FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT_INFO(STUDENT_ID),

    CONSTRAINT GRADE_SECTION_ID_FK
        FOREIGN KEY (SECTION_ID)
        REFERENCES SECTION_INFO(SECTION_ID),

    CONSTRAINT CHK_GRADE_TYPE_CODE
        CHECK (GRADE_TYPE_CODE IN ('FI', 'HM', 'MT', 'PA', 'PJ', 'QZ'))
);
